
[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[programs.localnet]
jam_settlement = "E51cxgBTJiNcBbG3DZfp4REDbcQb1PF7vmkoPqMR6bA2"
bebop_rfq      = "5kC1S7QB4xc5rbEVN6yz5PgEAEEASDthRqAwCaSuv2aW"
mock_swap      = "CKakx79upD27ZpcDdn9JZE27zXXF1CRDYNsBWp4tFqHo"
